### ISSUE TITLE
[super-task] JavaScript Tooling

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/geobricks-js#4]
Incorporate javascript developing tools.

As @fergonco says, each item will require a its own issue and discussion when addressed.

The following list is only an outline:
- Testing: mocha+chai or jasmine are both good candidates
- Coverage reports: istanbul? see what was used in Tunduras
- Documentation: see #3
- Code sanity: JsHint
- Compression/packing: Uglify2, cssmin
- HTML templating: handlebars
- Task automation: grunt*

(*)grunt has plugins to manage all the suggested tools: contrib-requirejs, mocha, contrib-jasmine, istanbul, jsdoc, contrib-jshint, contrib-uglify, contrib-cssmin, contrib-handlebars.

**Comment by fergonco** [comment]
I think this can be a huge issue, so everybody, if you want to push the adoption of a technology for some of the mentioned aspects, please open a new dedicated issue
