### ISSUE TITLE
Improve message-bus

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/geobricks-js#5]
- Add custom context parameter for listener (the _this_ problem in instance callbacks, see #2).
- Get rid of "event" parameter in callback function (not used, pollutes code).
- Rename methods to use the common pubsub pattern naming convention (better understandability).
- Add an "unsubscribe" method (for completion).
- Get rid of jQuery dependency (loose weight, gain control).

**Comment by oscarfonts** [comment]
An exampe where a callback function will loose the "this" context if it is not explicitly passed to listener:

``` javascript
define(["message-bus"], function(bus) {

    var Person = function(name) {
        this.name = name;

        this.getName = function() {
            return this.name;
        }

        bus.listen("rename", function(new_name) {
            this.name = new_name; // GAA!! "this" is not the instance context!
        });

    }

    return {
        createPerson: function(name) {
            return new Person(name);
        }
    }
});
```

Usage:

``` javascript
var factory = require("personFactory");
var person = factory.createPerson("Pepe");
person.getName(); // Returns "Pepe"

bus.send("rename", "Juan");
person.getName(); // GAA!! Won't be "Juan"!
```

**Comment by victorzinho** [comment]
I like the third version (messagebus3.js). I'm not sure if we can run into browser compatibility problems if we get rid of jQuery. But we are simply using "apply", so that wouldn't be the case, I guess.
